version: "3"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: root_user
      MINIO_ROOT_PASSWORD: root_pwd
    volumes:
      - minio_storage:/data
    ports:
      - '9000:9000/tcp'
      - "9001:9001"
    command: server --console-address ":9001" /data

volumes:
  minio_storage: